fix format

diff --git a/lamp_virtual_host b/lamp_virtual_host
--- a/lamp_virtual_host
+++ b/lamp_virtual_host
@@ -28,7 +28,7 @@
 #############################################################
 # Icons	and color	
 # https://www.techpaste.com/2012/11/print-colored-text-background-shell-script-linux/
-# https://apps.timwhitlock.info/emoji/tables/unicode		#
+# https://apps.timwhitlock.info/emoji/tables/unicode	
 #############################################################
 red='\033[0;31m'
 green='\033[0;32m'
@@ -40,11 +40,11 @@ icon_wait='\xE2\x8C\x9B'
 icon_rocket='\xF0\x9F\x9A\x80'
 
 #############################################################
-# Check Dependencies										#
+# Check Dependencies
 #############################################################
 # Check Apache
 if [ ! -d /etc/apache2 ]; then
-	printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}/etc/apache2${nocolor} is required.\n"
+  printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}/etc/apache2${nocolor} is required.\n"
 	exit 1;
 fi
 # Check php
@@ -54,11 +54,11 @@ if [ -z "$(ls -A "/etc/php")" ]; then
 fi
 
 #############################################################
-# Check Required variables									#
+# Check Required variables
 #############################################################
 if [ ! -d "$1" ]; then
-    printf "[${red}${icon_ko}${nocolor}] Type the directory that include your website (with final slash). ${red}N.B.${nocolor} rename the directory with website domain. Example: www.example.com\n"
-    exit 1;
+  printf "[${red}${icon_ko}${nocolor}] Type the directory that include your website (with final slash). ${red}N.B.${nocolor} rename the directory with website domain. Example: www.example.com\n"
+  exit 1;
 fi
 
 #domain name that is used for virtual host
@@ -78,7 +78,7 @@ fastcgi=""
 fastcgimodule="";
 
 #############################################################
-# User choises												#
+# User choises
 #############################################################
 echo ""
 echo "***************************"
@@ -90,17 +90,17 @@ echo ""
 PS3="Type 1 or 2: "
 actions=("development" "production")
 select action in "${actions[@]}"; do
-    case $action in
-        "development")
-		printf "[${green}${icon_ok}${nocolor}] Good, I will create the ssl certificate with certbot.\n"
-            	environment_type=$action
-		break;;
-        "production")
-		printf "[${green}${icon_ok}${nocolor}] Make sure you have added the domain dns that point to this server.\n"
-		environment_type=$action
-		break;;
-        *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
-    esac
+  case $action in
+    "development")
+      printf "[${green}${icon_ok}${nocolor}] Good, I will create the ssl certificate with certbot.\n"
+      environment_type=$action
+      break;;
+    "production")
+		  printf "[${green}${icon_ok}${nocolor}] Make sure you have added the domain dns that point to this server.\n"
+		  environment_type=$action
+		  break;;
+    *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
+  esac
 done
 
 # create/delete domain
@@ -114,21 +114,20 @@ echo ""
 PS3="Type 1 or 2: "
 actions=("create" "delete")
 select action in "${actions[@]}"; do
-    case $action in
-        "create")
-		#check if exists the virtual host
-	        if [ -d /var/www/"$domain" ]; then
-                	printf "[${red}${icon_ko}${nocolor}] Sorry, but this virtual host already exists.\n"
-                	exit 1;
-        	fi
-
-            	action_type=$action
-		break;;
-        "delete")
-            	action_type=$action
-		break;;
-        *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
-    esac
+  case $action in
+    "create")
+      #check if exists the virtual host
+      if [ -d /var/www/"$domain" ]; then
+        printf "[${red}${icon_ko}${nocolor}] Sorry, but this virtual host already exists.\n"
+       	exit 1;
+      fi
+      action_type=$action
+      break;;
+    "delete")
+      action_type=$action
+      break;;
+    *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
+  esac
 done
 printf "[${green}${icon_ok}${nocolor}] Good, I will to ${green}$action_type${nocolor} the virtual host. Now...\n"
 
@@ -142,16 +141,16 @@ echo ""
 S3="Type 1 or 2: "
 actions=("Yes" "No")
 select action in "${actions[@]}"; do
-    case $action in
-        "Yes")
-			# Check if exists
+  case $action in
+    "Yes")
+      # Check if exists
 			if ! command -v mysql &> /dev/null; then
 				printf "${red}${icon_ko}${nocolor} Sorry, but ${green}mysql${nocolor} is required.\n"
 				exit 1;
 			fi
 
 			#ok mysql is installed
-            		read -p "Type the database name: " database_name
+      read -p "Type the database name: " database_name
 			database_name=${database_name}
 
 			read -p "Type the database user: " database_user
@@ -162,13 +161,13 @@ select action in "${actions[@]}"; do
 			
 			sql="create database if not exists $database_name"
 			if [ "$action_type" == "delete" ]; then
-				sql="drop database $database_name;"
+        sql="drop database $database_name;"
 			fi
 			
 			printf "\nMysql log start: ----------------------------------------------------------------\n"	
 			#create/delete the database
 			if ! mysql -u$database_user -p$database_password  -e "$sql"; then
-				printf "Mysql log end: ----------------------------------------------------------\n"
+        printf "Mysql log end: ----------------------------------------------------------\n"
 				printf "[${red}${icon_ko}${nocolor}] Database errors. Solve this log errors messages.\n"
 				exit 1;
 			fi
@@ -190,15 +189,15 @@ select action in "${actions[@]}"; do
 				fi
 			fi
 			break;;
-        "No")
+    "No")
 			break;;
-        *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
-    esac
+    *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
+  esac
 done
 
 
 #########################################################
-# Delete the virtual host				#
+# Delete the virtual host
 #########################################################
 if [ "$action_type" = "delete" ]; then
 
@@ -206,8 +205,8 @@ if [ "$action_type" = "delete" ]; then
 
 	#check if exists the virtual host
 	if [ ! -d /var/www/"$domain" ]; then
-   		printf "[${red}${icon_ko}${nocolor}] Sorry, but this virtual host doesn't exists.\n"
-   		exit 1;
+    printf "[${red}${icon_ko}${nocolor}] Sorry, but this virtual host doesn't exists.\n"
+   	exit 1;
 	fi	
 
 	#delete the www directory
@@ -227,6 +226,12 @@ if [ "$action_type" = "delete" ]; then
 	sudo sed -i "/$domain/d" /etc/hosts
 	printf "[${green}${icon_ok}${nocolor}] website deleted from /etc/hosts!\n\n\n"
 
+  #if exists fail2ban reload 
+  if command -v fail2ban-client &> /dev/null; then
+    sudo fail2ban-client restart
+    printf "[${green}${icon_ok}${nocolor}] fail2ban restarted!\n\n\n"
+  fi
+
 	#print the final message
 	printf "[${green}${icon_rocket}${nocolor}] You have controlled your fear. Now, release your anger. Only your hatred can destroy me. Virtual host destroyed!\n"		
 
@@ -243,9 +248,9 @@ echo ""
 PS3="Do you want to use PHP-FPM (FastCGI Process Manager)?: "
 actions=("Yes" "No")
 select action in "${actions[@]}"; do
-    case $action in
-        "Yes")
-			printf "${yellow}${icon_wait}${nocolor} Choose the php-fpm version to use:\n"
+  case $action in
+    "Yes")
+		  printf "${yellow}${icon_wait}${nocolor} Choose the php-fpm version to use:\n"
 			echo ""
 			#choose the php-fpm versions
 			PS3='Type the choice number: '
@@ -276,11 +281,11 @@ select action in "${actions[@]}"; do
 			done
 			printf "[${green}${icon_ok}${nocolor}] Good, PHP-FPM will be used.\n"
 			break;;
-        "No")
+    "No")
 			printf "[${green}${icon_ok}${nocolor}] Good, PHP-FPM will not be used.\n"
-            break;;
-        *) printf "${red}${icon_ko}${nocolor} $REPLY isn't a valid option. Try again\n";;
-    esac
+      break;;
+    *) printf "${red}${icon_ko}${nocolor} $REPLY isn't a valid option. Try again\n";;
+  esac
 done
 
 #check if directory exists
@@ -324,42 +329,39 @@ ssl_support=''
 PS3="Type 1 or 2: "
 actions=("yes" "no")
 select action in "${actions[@]}"; do
-    case $action in
-        "yes")
-		# Check package dependencies
-		cert_package="mkcert"
-		if [ "production" == "$environment_type" ]; then
-			cert_package="certbot"
-		fi
+  case $action in
+    "yes")
+      # Check package dependencies
+      cert_package="mkcert"
+		  if [ "production" == "$environment_type" ]; then
+			  cert_package="certbot"
+		  fi
 
-		if ! command -v $cert_package &> /dev/null; then
-			printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}$cert_package${nocolor} is required. Install it before!\n"
-			exit 1;
-		fi
+		  if ! command -v $cert_package &> /dev/null; then
+			  printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}$cert_package${nocolor} is required. Install it before!\n"
+			  exit 1;
+		  fi
 
-		# check if ssl mod is enabled
-		if [ ! -f "/etc/apache2/mods-enabled/ssl.load" ]; then
- 			printf "[${red}${icon_ko}${nocolor}] Enable SSL on Apache2 with ${green}sudo a2enmod ssl\n"
+		  # check if ssl mod is enabled
+		  if [ ! -f "/etc/apache2/mods-enabled/ssl.load" ]; then
+ 			  printf "[${red}${icon_ko}${nocolor}] Enable SSL on Apache2 with ${green}sudo a2enmod ssl\n"
    			exit 1;
-		fi
+		  fi
 
-		#create the ssl certificate
-		if [ "development" == "$environment_type" ]; then
-			mkcert $domain > /dev/null 2>&1
-            		ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerAdmin webmaster@localhost\nServerName $domain\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /var/www/$domain/$domain.pem\nSSLCertificateKeyFile /var/www/$domain/$domain-key.pem\n\n$fastcgi</VirtualHost>\n</IfModule>"
-		else
-			sudo certbot certonly --cert-name $domain -d $domain --pre-hook "service apache2 stop" --post-hook "service apache2 start"
-			ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerAdmin webmaster@localhost\nServerName $domain\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /etc/letsencrypt/live/$domain/fullchain.pem\nSSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem\n\n$fastcgi</VirtualHost>\n</IfModule>"
-	
-		fi
-		printf "[${green}${icon_ok}${nocolor}] SSL Certificate created with success!\n"
-
-
-		break;;
-        "no")
-		break;;
-        *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
-    esac
+		  #create the ssl certificate
+		  if [ "development" == "$environment_type" ]; then
+			  mkcert $domain > /dev/null 2>&1
+        ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerAdmin webmaster@localhost\nServerName $domain\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /var/www/$domain/$domain.pem\nSSLCertificateKeyFile /var/www/$domain/$domain-key.pem\n\n$fastcgi</VirtualHost>\n</IfModule>"
+		  else
+			  sudo certbot certonly --cert-name $domain -d $domain --pre-hook "service apache2 stop" --post-hook "service apache2 start"
+			  ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerAdmin webmaster@localhost\nServerName $domain\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /etc/letsencrypt/live/$domain/fullchain.pem\nSSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem\n\n$fastcgi</VirtualHost>\n</IfModule>"
+      fi
+      printf "[${green}${icon_ok}${nocolor}] SSL Certificate created with success!\n"
+      break;;
+    "no")
+		  break;;
+    *) printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n";;
+  esac
 done
 
 #set the directory permissions
@@ -385,6 +387,12 @@ sudo a2ensite $domain.conf > /dev/null 2>&1
 #restart apache
 sudo service apache2 restart > /dev/null 2>&1
 printf "[${green}${icon_ok}${nocolor}] Apache reloaded!\n"
+
+#if exists fail2ban reload 
+if command -v fail2ban-client &> /dev/null; then
+  sudo fail2ban-client restart
+  printf "[${green}${icon_ok}${nocolor}] fail2ban restarted!\n\n\n"
+fi
 
 #Add the domain to hosts
 sudo sh -c "echo '127.0.0.1	$domain' >> /etc/hosts"
