fix #1

diff --git a/lamp_virtual_host b/lamp_virtual_host
--- a/lamp_virtual_host
+++ b/lamp_virtual_host
@@ -85,8 +85,9 @@ environment_type=""
 #action type
 action_type=""
 
-#php fast cgi
+#php fastcgi
 fastcgi=""
+fastcgi_ssl=""
 
 #############################################################
 # User choises
@@ -290,7 +291,20 @@ select action in "${actions[@]}"; do
         printf "[${red}${icon_ko}${nocolor}] $REPLY isn't a valid option. Try again\n"
         exit 1
       fi
-      fastcgi="<FilesMatch \.php$>\nSetHandler \"proxy:unix:/run/php/php$php_version-fpm.sock|fcgi://localhost\"\n</FilesMatch>\n"
+      
+      #check if exists fast cgi module for debian or ubuntu
+      if [ -n "$(sudo ls /etc/apache2/mods-enabled/ | grep fcgid.conf)" ]; then
+        #config for apache fcgid module (in debian)
+        fastcgi="\n\n<FilesMatch \.php$>\nSetHandler \"proxy:unix:/run/php/php$php_version-fpm.sock|fcgi://localhost\"\n</FilesMatch>\n"
+        fastcgi_ssl=$fastcgi
+      elif [ -n "$(sudo ls /etc/apache2/mods-enabled/ | grep fastcgi.conf)" ]; then
+        #config for fastcgi (in ubuntu)
+        fastcgi="\n\n<IfModule mod_fastcgi.c>\n<FilesMatch \".+\.ph(p[345]?|t|tml)\$\">\nSetHandler php${php_version//./}-fcgi-www\n</FilesMatch>\n</IfModule>\n"
+        fastcgi_ssl="<FilesMatch \"\.(cgi|shtml|phtml|php)\$\">\nSSLOptions +StdEnvVars\n</FilesMatch>\n<Directory /usr/lib/cgi-bin>\nSSLOptions +StdEnvVars\n</Directory>$fastcgi\n"
+      else
+        printf "[${red}${icon_ko}${nocolor}] Sorry, but the fastcgi module is required. Install it before.\n"
+        exit 1
+      fi
       break
     done
     printf "[${green}${icon_ok}${nocolor}] Good, PHP-FPM will be used.\n"
@@ -368,10 +382,10 @@ select action in "${actions[@]}"; do
     #create the ssl certificate
     if [ "development" == "$environment_type" ]; then
       mkcert $hosts_domain >/dev/null 2>&1
-      ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerName $domain\nServerAlias $domain_alias\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /var/www/$domain/$domain.pem\nSSLCertificateKeyFile /var/www/$domain/$domain-key.pem\n\n$fastcgi</VirtualHost>\n</IfModule>"
+      ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerName $domain\nServerAlias $domain_alias\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /var/www/$domain/$domain.pem\nSSLCertificateKeyFile /var/www/$domain/$domain-key.pem\n\n$fastcgi_ssl</VirtualHost>\n</IfModule>"
     else
       sudo certbot certonly --cert-name $domain -d $certbot_domains --pre-hook "systemctl stop apache2.service" --post-hook "systemctl start apache2.service"
-      ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerName $domain\nServerAlias $domain_alias\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /etc/letsencrypt/live/$domain/fullchain.pem\nSSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem\n\n$fastcgi</VirtualHost>\n</IfModule>"
+      ssl_support="\n\n<IfModule mod_ssl.c>\n\n<VirtualHost _default_:443>\nServerName $domain\nServerAlias $domain_alias\n\nDocumentRoot /var/www/$domain/public_html\n\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\nSSLEngine on\n\nSSLCertificateFile /etc/letsencrypt/live/$domain/fullchain.pem\nSSLCertificateKeyFile /etc/letsencrypt/live/$domain/privkey.pem\n\n$fastcgi_ssl</VirtualHost>\n</IfModule>"
     fi
     printf "[${green}${icon_ok}${nocolor}] SSL Certificate created with success!\n"
     break
@@ -397,7 +411,7 @@ sudo touch /etc/apache2/sites-available/$domain.conf
 printf "[${green}${icon_ok}${nocolor}] Apache config file created with success!\n"
 
 #create the virtual host apache file
-sudo sh -c "echo '<VirtualHost *:80>\n\nServerName $domain\nServerAlias $domain_alias\nSetEnv PATH \"/var/www/$domain/public_html\"\nDocumentRoot /var/www/$domain/public_html\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined\n\n</VirtualHost>$ssl_support' >> /etc/apache2/sites-available/$domain.conf"
+sudo sh -c "echo '<VirtualHost *:80>\n\nServerName $domain\nServerAlias $domain_alias\nSetEnv PATH \"/var/www/$domain/public_html\"\nDocumentRoot /var/www/$domain/public_html\nErrorLog /var/www/$domain/log/error.log\nCustomLog /var/www/$domain/log/access.log combined$fastcgi\n\n</VirtualHost>$ssl_support' >> /etc/apache2/sites-available/$domain.conf"
 printf "[${green}${icon_ok}${nocolor}] Virtual host created! For extra options, edit this file: /etc/apache2/sites-enabled/$domain.conf\n"
 
 #Enable the site
